services:
  mongo:
    image: mongo:latest
    container_name: lumos-backend
    environment:
      MONGO_INITDB_DATABASE: lumos
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
